### ISSUE TITLE
fix windows

### ISSUE THREAD

**Issue by g0dm0d** [g0dm0d/yogurt#6]

**Comment by g0dm0d** [comment]
In java, the "-cp" argument is formatted differently. The character ";" is used as a separator. 

windows:
```bash
java -cp C:\lib\mylibrary.jar;C:\MyProject\bin MyProgram
```
linux/macos:
```bash
java -cp /home/user/lib/mylibrary.jar:/home/user/MyProject/bin MyProgram
```

Also the paths should be changed from "/" to "\\".

I hate windows :disappointed:

**Comment by ModerNik** [comment]
path can be "/" in windows
commit #3d6061e
